services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: f1_api
        env_file:
            - .env
        ports:
            - '${PORT}:${PORT}'
        networks:
            - backend

networks:
    backend:
